# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [33]:
import numpy as np

#### 2. Print your NumPy version.

In [34]:
np.__version__

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [35]:
a = np.random.random((2,3,5))

In [36]:
a = np.random.random_sample((2,3,5))

In [37]:
a = np.random.rand(2,3,5)

#### 4. Print *a*.


In [38]:
print(a)

[[[0.77224949 0.68888018 0.91582821 0.04920542 0.31613084]
  [0.38724799 0.24359216 0.11898231 0.77553712 0.86191671]
  [0.25935185 0.90378414 0.47732606 0.49813256 0.71788956]]

 [[0.36464898 0.15270571 0.0821294  0.77081978 0.59089595]
  [0.63414477 0.8679926  0.54428755 0.60361905 0.69308446]
  [0.15875189 0.0270542  0.24433504 0.16778616 0.54748069]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [39]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [40]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [41]:
a.size

30

In [42]:
b.size

30

In [43]:
if a.size == b.size:
    print(True)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [44]:
a+b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

No, because **a** doesn't have the same shape as **b**

#### 9. Reshape *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the reshaped array to variable *c*.

In [45]:
c = b.reshape((2,3,5))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [46]:
d = a + c
d

array([[[1.77224949, 1.68888018, 1.91582821, 1.04920542, 1.31613084],
        [1.38724799, 1.24359216, 1.11898231, 1.77553712, 1.86191671],
        [1.25935185, 1.90378414, 1.47732606, 1.49813256, 1.71788956]],

       [[1.36464898, 1.15270571, 1.0821294 , 1.77081978, 1.59089595],
        [1.63414477, 1.8679926 , 1.54428755, 1.60361905, 1.69308446],
        [1.15875189, 1.0270542 , 1.24433504, 1.16778616, 1.54748069]]])

Because now **a** has the same shape as **c**

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [47]:
print(a)

[[[0.77224949 0.68888018 0.91582821 0.04920542 0.31613084]
  [0.38724799 0.24359216 0.11898231 0.77553712 0.86191671]
  [0.25935185 0.90378414 0.47732606 0.49813256 0.71788956]]

 [[0.36464898 0.15270571 0.0821294  0.77081978 0.59089595]
  [0.63414477 0.8679926  0.54428755 0.60361905 0.69308446]
  [0.15875189 0.0270542  0.24433504 0.16778616 0.54748069]]]


In [48]:
print(d)

[[[1.77224949 1.68888018 1.91582821 1.04920542 1.31613084]
  [1.38724799 1.24359216 1.11898231 1.77553712 1.86191671]
  [1.25935185 1.90378414 1.47732606 1.49813256 1.71788956]]

 [[1.36464898 1.15270571 1.0821294  1.77081978 1.59089595]
  [1.63414477 1.8679926  1.54428755 1.60361905 1.69308446]
  [1.15875189 1.0270542  1.24433504 1.16778616 1.54748069]]]


**d=a+1**

**12. Multiply a and c. Assign the result to e.**

In [49]:
e = a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [50]:
e

array([[[0.77224949, 0.68888018, 0.91582821, 0.04920542, 0.31613084],
        [0.38724799, 0.24359216, 0.11898231, 0.77553712, 0.86191671],
        [0.25935185, 0.90378414, 0.47732606, 0.49813256, 0.71788956]],

       [[0.36464898, 0.15270571, 0.0821294 , 0.77081978, 0.59089595],
        [0.63414477, 0.8679926 , 0.54428755, 0.60361905, 0.69308446],
        [0.15875189, 0.0270542 , 0.24433504, 0.16778616, 0.54748069]]])

In [51]:
a

array([[[0.77224949, 0.68888018, 0.91582821, 0.04920542, 0.31613084],
        [0.38724799, 0.24359216, 0.11898231, 0.77553712, 0.86191671],
        [0.25935185, 0.90378414, 0.47732606, 0.49813256, 0.71788956]],

       [[0.36464898, 0.15270571, 0.0821294 , 0.77081978, 0.59089595],
        [0.63414477, 0.8679926 , 0.54428755, 0.60361905, 0.69308446],
        [0.15875189, 0.0270542 , 0.24433504, 0.16778616, 0.54748069]]])

**e** is equal to **a**, because **a*1=a**

In [52]:
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [53]:
d_max = d.max()
d_max

1.915828210166604

In [54]:
d_min = d.min()
d_min

1.02705419885937

In [55]:
d_mean = d.mean()
d_mean

1.4811930272493363

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [56]:
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [57]:
for arrays in range(2):
    for columns in range(3):
         for rows in range(5):
            i = d[arrays][columns][rows]
            if (i>d_min) and (i<d_mean):
                 i = 25
            elif (i>d_mean) and (i<d_max):
                i = 75
            elif (i == d_mean):
                i = 50
            elif (i == d_min):
                i = 0
            elif (i == d_max):
                i = 100
            f[arrays][columns][rows] = i

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [58]:
print(d)

[[[1.77224949 1.68888018 1.91582821 1.04920542 1.31613084]
  [1.38724799 1.24359216 1.11898231 1.77553712 1.86191671]
  [1.25935185 1.90378414 1.47732606 1.49813256 1.71788956]]

 [[1.36464898 1.15270571 1.0821294  1.77081978 1.59089595]
  [1.63414477 1.8679926  1.54428755 1.60361905 1.69308446]
  [1.15875189 1.0270542  1.24433504 1.16778616 1.54748069]]]


In [59]:
print(f)

[[[ 75.  75. 100.  25.  25.]
  [ 25.  25.  25.  75.  75.]
  [ 25.  75.  25.  75.  75.]]

 [[ 25.  25.  25.  75.  75.]
  [ 75.  75.  75.  75.  75.]
  [ 25.   0.  25.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.